name: plantelpro_ui
description: Plantelpro UI library
version: 0.0.1
publish_to: none

environment: 
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_asset_generator: ^1.0.2
  flutter_svg: ^2.0.7
  file_picker: ^5.2.5 
  vector_graphics: ^1.1.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/src/assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: lib/src/assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/src/assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: lib/src/assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/src/assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: lib/src/assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/src/assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: lib/src/assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/src/assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: lib/src/assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/src/assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: lib/src/assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
  
  

flutter_gen:
  assets:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true