// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5PlaYAUHgohHwIoZ7Hns9fkAcG9RgiJM',
    appId: '1:574791170944:web:b3e399274d234ec17d1f65',
    messagingSenderId: '574791170944',
    projectId: 'plantelpro',
    authDomain: 'plantelpro.firebaseapp.com',
    storageBucket: 'plantelpro.firebasestorage.app',
    measurementId: 'G-931YH9CMRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoY8nU89kGVTJfdMQwmF2tLGjneigbXgg',
    appId: '1:574791170944:android:7575ee69d4482ef47d1f65',
    messagingSenderId: '574791170944',
    projectId: 'plantelpro',
    storageBucket: 'plantelpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr-fOpNRmjx7Dh9A_to3WLcvpK14ThpY0',
    appId: '1:574791170944:ios:d55b030d75c81e767d1f65',
    messagingSenderId: '574791170944',
    projectId: 'plantelpro',
    storageBucket: 'plantelpro.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.plantelpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr-fOpNRmjx7Dh9A_to3WLcvpK14ThpY0',
    appId: '1:574791170944:ios:336ecbccdd2877497d1f65',
    messagingSenderId: '574791170944',
    projectId: 'plantelpro',
    storageBucket: 'plantelpro.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5PlaYAUHgohHwIoZ7Hns9fkAcG9RgiJM',
    appId: '1:574791170944:web:b3e399274d234ec17d1f65',
    messagingSenderId: '574791170944',
    projectId: 'plantelpro',
    authDomain: 'plantelpro.firebaseapp.com',
    storageBucket: 'plantelpro.firebasestorage.app',
    measurementId: 'G-931YH9CMRC',
  );
}
